name: Deploy App

on:
  workflow_run:
    workflows: ["Build App"]
    branches: [main]
    types:
      - completed

env:
  AWS_REGION: us-east-1
  ECR_REPOSITORY: gpt-discord-chatbot
  IMAGE_NAME: gpt-discord-chatbot

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Download artifact from CI
      uses: actions/download-artifact@v2
      with:
        name: ${{ env.IMAGE_NAME }}
        path: .
        
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}
        
    - name: Login to AWS ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
        
    - name: Push Docker image to ECR
      run: |
        docker tag ${{ env.IMAGE_NAME }}:latest ${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.ECR_REPOSITORY }}:latest
        docker push ${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.ECR_REPOSITORY }}:latest
