name: Build App

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

env:
  IMAGE_NAME: gpt-discord-chatbot
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Build Docker image
      run: |
        docker build -t ${{ env.IMAGE_NAME }} .

    - name: Save Docker image
      run: |
        docker save ${{ env.IMAGE_NAME }} > ${{ env.IMAGE_NAME }}.tar

    - name: Publish Docker image as artifact
      uses: actions/upload-artifact@v2
      with:
        name: ${{ env.IMAGE_NAME }}
        path: ${{ env.IMAGE_NAME }}.tar
